config/routes.rb
Jsovet::Application.routes.draw do

  resources :recipes do
    resources :recipes_comments do
      member do
        get 'publish'
      end
    end
  end

  resources :reviews do
    member do
      post :publish
    end
  end

  resources :answers
  resources :relative_questions, :only => [:index, :create]

  resources :questions do
    resources :relative_questions, :only => [:index, :create]
    resources :answers
    collection do
      get "hidden"
      post "sort"
    end
    member do
      get 'publish_on_main', 'not_publish_on_main'
    end
  end

  devise_for :users

  namespace :admin do
    resources :categories, :only => %w{index create edit update}
    resources :recipe_categories, :only => %w{index create edit update}
    resource :dashboard, :only => %w{show}, :controller => "dashboard"
    resources :articles, :only => "index"
    resources :stores
    resources :main_articles, :only => "index"
    resources :main_questions, :only => "index"
    resources :unpublished_articles, :only => "index"
    resources :questions, :only => "index"
    resources :containers
  end

  resources :categories, :only => %w{index} do
    resources :articles
  end

  resources :recipe_categories, :only => %w{index, show} do
    resources :recipes
  end

  resources :containers, :only => %w{index}

  resources :stores, :only => %w{show index} do
    collection do
      post "sort"
    end
  end
  resources :shoping_carts, :only => %w{index} do
    collection do
      get 'clear'
      get 'new_mail'
      post 'send_mail'
    end

    member do
      get 'add'
      get 'delete'
    end
  end

  resources :articles, :only => %w{new create edit update index} do

    collection do
      get 'my'
      post 'preview'
      post 'sort'
    end

    member do
      get 'publish', 'delete', 'publish_on_main', 'not_publish_on_main'
    end

    resources :comments, :only => %w{create update}
    resources :relative_articles, :only => %w{index create}
  end

  resources :images do
    collection do
      put "update_images"
    end
  end

  match 'search/index' => 'search#index', :as => :search
  match 'how_to_buy' => 'home#how_to_buy', :as => :how_to_buy
  get "mayskiy_med_2013" => "home#mayskiy_med", :as => :mayskiy
  get "contacts" => "home#contacts", :as => :contacts

  root :to => "home#index"
end

app/models/store.rb
require 'acts_as_list'
class Store < ActiveRecord::Base
  acts_as_list
  attr_accessor :product
  attr_accessible :name, :description, :where_from, :honey_sort,
                  :logo, :on_index, :on_top, :shown, :price, :price_three_liters, :price_one_liter, :product,
                  :prod, :fresh, :position, :logo_name, :gather_place,
                  :certificate


  has_attached_file :logo, :styles => {:big => "400x400>", :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :gather_place, :styles => {:big => "400x400>", :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :certificate, :styles => {:big => "600x900>", :medium => "300x300>", :thumb => "100x100>" }

  validates_presence_of :name, :description, :where_from,  :price, :price_three_liters, :price_one_liter
  #validates_presence_of :honey_sort, :if => Proc.new{ |store| store.product == "true" }



  scope :at_index, where(:on_index => true).order(:position)
  scope :at_top, where(:on_top => true)
  scope :shown, where(:shown => true).order(:position)

  def self.short_weight
    range = (100..1000)
    range.step(100).to_a
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < ApplicationController
  load_and_authorize_resource :store
  uses_tiny_mce :options => {
                            :theme => 'advanced',
                            :theme_advanced_resizing => true,
                            :theme_advanced_resize_horizontal => false,
                            :theme_advanced_toolbar_location => "top",
                            :theme_advanced_toolbar_align => "left",
                            :theme_advanced_statusbar_location => "bottom",
                            :theme_advanced_buttons1 => %w{ bold italic underline fontselect fontsizeselect formatselect newdocument},
                            :theme_advanced_buttons2 => %w{ justifyleft justifycenter justifyright bullist numlist undo redo }
                            }

  def index
    @stores = Store.order(:position)
    authorize! :update, @stores
  end

  def new
  end

  def create
    if @store.save
      redirect_to :action => :index, :notice => t("stores.successful.create")
    else
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @store.update_attributes(params[:store])
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def show
  end

  def delete
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_filter :add_crumb, :only => :show
  after_filter :authorize, :only => [:sort]
  load_and_authorize_resource :store, :except => [:sort]

  def index
    @stores = Store.shown
  end

  def show
    @store = Store.find(params[:id])
    add_breadcrumb @store.name, store_path(@store)
  end

  def sort
    params[:store].each_with_index do |id, index|
      Store.update_all({:position => index+1}, {:id => id})
    end
  render :nothing => true
  
  end

  private
  def add_crumb
    add_breadcrumb "Магазин мёда", stores_path
  end

end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper

  def yes_no(bool)
    bool == true ? "Да" : "Нет"
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_store.html.erb
<div class="product">
    <% if store.on_top? %>
      <span class="top"></span>
    <% elsif store.fresh %>
      <span class="top fresh"></span>
    <% end %>
    <% if store.honey_sort %>
      <%= sort_image store.honey_sort %>
    <% else %>
      <div style="width: 180px; height: 180px; float: left;">&nbsp;</div>
    <% end %>
    <h4><%= link_to store.name, store_path(store) %></h4>
    <span><%= store.where_from %></span>
    <div class="price">
      <% if store.prod? %>
        <p><%= store.price/10 %> Р.</p>
      <% else %>
        <p><%= store.price %> Р. килограмм </p>
        <p><%= store.price_one_liter %> Р. 1 литр</p>
        <p><%= store.price_three_liters %> Р. 3 литра</p>
      <% end %>
      <br/>
      <div>
      <%= form_tag(add_shoping_cart_path(store), :remote => true, :method => :get) do %>
        <table border="0">
          <tr>
            <td valign="bottom" >
              <% if store.prod?%>
                <%= select_tag "amount", options_for_select(Store.short_weight.map{|s| ["#{s} грамм", s]}), :class=>"select" %>
              <% else %>
                <%= select_tag "amount", options_for_select([["1 килограмм", "1000"], ["1 литр(1400 грамм)", "1400"], ["3 литра(4500 грамм)", "4500"]]), :class=>"select" %>
              <% end %>
            </td>
            <td valign="top">
              <%= submit_tag "В корзину", :class => "buy" %>
            </td>
          </tr>
        </table>
      <% end %>
      </div>
    </div>
</div><!-- END product -->

app/views/stores/index.html.erb
<%= title("Магазин меда :: Мед на дом") %>
<%= description(" Здесь вы можете заказать натуральный мёд с доставкой на дом, а также прочитать описание предлагаемых сортов.")%>
<div class="posts single">
  <h1><%= t(".title") %></h1>
</div>

<div class="products">
    <%= render :partial => "store", :collection => @stores %>
</div><!-- END products -->

app/views/stores/show.html.erb
<div class="posts single">
  <h1><%= @store.name %></h1>
</div>
<div class="product">
    <% if @store.on_top? %>
      <span class="top"></span>
    <% end %>
    <%= sort_image @store.honey_sort %>
    <span><%= @store.where_from %></span>
    <div class="post">
      <%= RedCloth.new( @store.description).to_html.html_safe %>
      <% if @store.certificate? %>
       <div id="zoom">
       <span class="cert">
              Сертификат соответствия:
          <%= link_to image_tag(@store.certificate.url(:thumb), :alt =>  "certificate", :id =>"picture"), @store.certificate.url(:big), :class => "zoom" %>
       </span>
      </div>
      <% end %>
      <p><script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
<div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="link" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,gplus"></div> </p>
    </div>

    <br/>
    <% if @store.logo? %>
      <% if @store.logo_name? %>
      <b><%= @store.logo_name %></b>
      <% end %>
      <span>
        <%= image_tag @store.logo.url(:medium), :id=>"picture" %>
      </span>
    <% end %>
    <br/>
    <% if @store.gather_place? %>
    <b>Место сбора</b>
      <span>
        <%= image_tag @store.gather_place.url(:big), :id=>"picture" %>
      </span>
    <% end %>
    <div class="price">
      <% if @store.prod? %>
        <p><%= @store.price/10 %> Р.</p>
      <% else %>
        <p><%= @store.price %> Р. 1кг.</p>
        <p><%= @store.price_one_liter %> Р. 1 литр</p>
        <p><%= @store.price_three_liters %> Р. 3 литра</p>
      <% end %>
      <%= form_tag(add_shoping_cart_path(@store), :remote => true, :method => :get) do %>
        <table border="0">
          <tr>
            <td valign="bottom">
              <% if @store.prod?%>
                <%= select_tag "amount", options_for_select(Store.short_weight.map{|s| ["#{s} грамм", s]}), :class=>"select" %>
              <% else %>
                <%= select_tag "amount", options_for_select([["1 килограмм", "1000"], ["1 литр(1400 грамм)", "1400"], ["3 литра(4500 грамм)", "4500"]]), :class=>"select" %>
              <% end %>
            </td>
            <td valign="top">
              <%= submit_tag "В корзину", :class => "buy" %>
            </td>
          </tr>
        </table>
      <% end %>
    </div>
</div><!-- END product -->