config/routes.rb
Jsovet::Application.routes.draw do

  resources :recipes do
    resources :recipes_comments do
      member do
        get 'publish'
      end
    end
  end

  resources :reviews do
    member do
      post :publish
    end
  end

  resources :answers
  resources :relative_questions, :only => [:index, :create]

  resources :questions do
    resources :relative_questions, :only => [:index, :create]
    resources :answers
    collection do
      get "hidden"
      post "sort"
    end
    member do
      get 'publish_on_main', 'not_publish_on_main'
    end
  end

  devise_for :users

  namespace :admin do
    resources :categories, :only => %w{index create edit update}
    resources :recipe_categories, :only => %w{index create edit update}
    resource :dashboard, :only => %w{show}, :controller => "dashboard"
    resources :articles, :only => "index"
    resources :stores
    resources :main_articles, :only => "index"
    resources :main_questions, :only => "index"
    resources :unpublished_articles, :only => "index"
    resources :questions, :only => "index"
    resources :containers
  end

  resources :categories, :only => %w{index} do
    resources :articles
  end

  resources :recipe_categories, :only => %w{index, show} do
    resources :recipes
  end

  resources :containers, :only => %w{index}

  resources :stores, :only => %w{show index} do
    collection do
      post "sort"
    end
  end
  resources :shoping_carts, :only => %w{index} do
    collection do
      get 'clear'
      get 'new_mail'
      post 'send_mail'
    end

    member do
      get 'add'
      get 'delete'
    end
  end

  resources :articles, :only => %w{new create edit update index} do

    collection do
      get 'my'
      post 'preview'
      post 'sort'
    end

    member do
      get 'publish', 'delete', 'publish_on_main', 'not_publish_on_main'
    end

    resources :comments, :only => %w{create update}
    resources :relative_articles, :only => %w{index create}
  end

  resources :images do
    collection do
      put "update_images"
    end
  end

  match 'search/index' => 'search#index', :as => :search
  match 'how_to_buy' => 'home#how_to_buy', :as => :how_to_buy
  get "mayskiy_med_2013" => "home#mayskiy_med", :as => :mayskiy
  get "contacts" => "home#contacts", :as => :contacts

  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.published.order(:position)
    @stores = Store.shown.at_index
  end

  def contacts

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_article.html.erb
<h2><%= link_to article.category.name, category_articles_path(article.category_id)%> &rarr; <%= link_to article.name, category_article_path(article.category_id, article.id) %></h2>
<div class="article body">
  <%= article.preview %>
</div>
  <div class="post_info">
          <div class="author">
                  <a href="#"><%= image_tag article.user.avatar.url(:thumb), :class=>"thumb", :width=>"36", :height=>"36" %></a>
                  <p><%= t("articles.article.publish_on")  %>: <%= l( article.updated_at ) %></p>
                  <p><%= t("articles.article.author")  %>: <%=  article.author %></p>
                  <% if params[:action] == "my" %>
                    <p class="article status"> 
                      <%= t("articles.article.status") %>: <%= article.aasm_status %>
                    </p>
                  <% end %>
          </div><!-- END author -->
          
          <ul>
                <% if can? :update, article %>
                  <li class="edit">
                    <%= link_to t("edit"), edit_article_path(article) %>
                  </li>
                  <% if can? :destroy, article %>
                    <li class="shift_del">
                      <%= link_to t("destroy"), article_path(article), :method => :delete%>
                    </li>
                  <% end %>
                  <% if can? :publish, article and not article.publics? %>
                    <li class="edit">
                      <%= link_to t("publish"), publish_article_path(article) %>
                    </li>
                  <% end %>
                  <% if can? :delete, article %>
                    <li class="del">
                      <%= link_to t("delete"), delete_article_path(article), :confirm => t("confirm") %>
                    </li>
                  <% end %>
                <% end %>
          </ul>
  </div><!-- END post_info -->

app/views/home/contacts.html.erb
<% content_for :map do %>
<script charset="utf-8" src="https://clck.yandex.ru/jclck/dtype=stred/pid=443/cid=71834/path=map/rnd=0.48028539191000164/*https://maps.yandex.ru/"></script>
<script src="http://api-maps.yandex.ru/2.0/?load=package.full&amp;lang=ru-RU" type="text/javascript"></script>
<script type="text/javascript">
        // Как только будет загружен API и готов DOM, выполняем инициализацию
        //http://maps.yandex.ru/-/CVVyVW2n
        ymaps.ready(init);

        function init () {
            var myMap = new ymaps.Map("map", {
                    center: [47.262659, 39.857008],
                    zoom: 16,
                    type: "yandex#map"
                }),

                // Создаем метку. При создании метки указываем ее свойство -  текст для отображения в иконке.38.863351,44.268141
                myPlacemark = new ymaps.Placemark([47.262601, 39.858896], {
                    // Свойства
                    // Текст метки
                    iconContent: "Ростовская область, \n г. Аксай, проспект Ленина, д. 12"
                }, {
                    // Опции
                    // Иконка метки будет растягиваться под ее контент
                    preset:'twirl#blueStretchyIcon'
                });

         // В метод add можно передать строковый идентификатор
            // элемента управления и его параметры.
            myMap.controls
                // Кнопка изменения масштаба
                .add('zoomControl')
                // Список типов карты
                .add('typeSelector')
                // Кнопка изменения масштаба - компактный вариант
                // Расположим её справа
                //.add('smallZoomControl', { right: 5, top: 75 })
                // Стандартный набор кнопок
                .add('mapTools');

            // Также в метод add можно передать экземпляр класса, реализующего определенный элемент управления.
            // Например, линейка масштаба ('scaleLine')
            myMap.controls
                .add(new ymaps.control.ScaleLine())
                // В конструкторе элемента управления можно задавать расширенные
                // параметры, например, тип карты в обзорной карте
                .add(new ymaps.control.MiniMap({
                    type: 'yandex#publicMap'
                }));


            // Добавляем метки на карту
            myMap.geoObjects
                .add(myPlacemark)
                .add(myGeoObject);
        }
    </script>
<% end %>
<%= title("Контакты :: Мед на дом") %>
<%= description("Наш адрес: Ростовская область, г. Аксай, проспект Ленина, д. 12, офис 315 А.") %>

<div class="posts single">
  <h1>Контакты</h1>
</div>


<div class="post">
  <p>
    Адрес: Ростовская область, г. Аксай, проспект Ленина, д. 12, офис 315 А.
  </p>
  <p>
   Телефон для связи: +7(928)604-78-34
  </p>
  <p>
    Email: <%= mail_to "zakaz@mednadom.com", "zakaz@mednadom.com" %>
  </p>
</div>

<p>
  <div id="map" style="width:600px; height:600px">
  </div>
</p>

app/views/home/how_to_buy.html.erb
<%= title("Как купить мед у нас :: Мед на дом") %>
<%= description("Как правильно составить заказ? Читайте на этой страничке.") %>
<div class="posts single">
  <h1>Как купить мёд</h1>

<div class="post marging_li">
<p>
<b>Уважаемые покупатели!</b>
</p>

<p>
  <b>Наш интернет-магазин осуществляет доставку по Ростову на Дону и регионам России.</b>
</p>

<p>
  <b><u>Курьерская доставка по Ростову-на Дону:</u></b>
</p>

<p>
  <ul>
    <li> срок 1-3 дня со дня размещения заказа
      <li><b><u>бесплатно</u></b> осуществляется доставка от 2-х литров  мёда
        <li>стоимость доставки заказа <b><u>мене 2-х литров</u></b> составит 250 руб.
  </ul>
</p>



<p>
 Оплата производится курьеру наличными средствами. Вы получаете всю необходимую документацию.
</p>



<p>
  <b>Обратите внимание, что мы снабжаем  заказ бесплатным пробником. Обязательно продегустируйте его мёд в присутствии курьера!</b>
</p>

<p>
  В случае, если мёд <b> не подошёл вам по какой-либо из объективных причин</b> (вкус, цвет, запах, консистенция)<b> вы можете отказаться от его покупки.</b> Услуги курьера при этом не оплачиваются.
</p>



<p>

  <b><u>Варианты доставки по России:</u></b>
</p>

<p>

  <ul>
    <li><b>Почта России.</b> Один из самых надёжных и недорогих, но не самый быстрый способ доставки.</li>
  </ul>

</p>
<p>

  Из-за особенностей упаковки товара мы принимаем заявки на посылки весом <b>3 кг.,  4 кг., 5 кг. и 6 кг.</b>

</p>
<p>
  <b>При заказе посылок  весом более 6 кг, «Почтой России»  стоимость пересылки бесплатно!</b>
</p>

<p>

<ul>
  <li><b>EMS Почта России.</b>  Экспресс-доставка Почтой России. Сроки и стоимость доставки смотрите здесь: <%= link_to "http://www.emspost.ru/ru/calc/", 'http://www.emspost.ru/ru/calc/' %></li>
  <li><b>«СПСР – Экспресс».</b>  Крупнейший российский экспресс-оператор. Доставка «от двери до двери», в удобное для вас  время.  Сроки и стоимость доставки здесь: <%= link_to "http://www.spsr.ru/ru/service/calculator", 'http://www.spsr.ru/ru/service/calculator' %></li>
</ul>
</p>


<p>
<b><u>Варианты оплаты:</u></b>

<ul>
  <li>  <b>наложенный платёж</b> – это 100% оплата товара при получении на почте или с помощью курьерской службы СПСР-экспресс.

    <b>Внимание! Почта России берёт комиссию за отправку денежного перевода, который  возвращается нам.</b>  Расчёты здесь: <%= link_to " http://www.russianpost.ru/rp/servise/ru/home/finuslug/cybermoney_russia", 'http://www.russianpost.ru/rp/servise/ru/home/finuslug/cybermoney_russia' %>
  </li>

  <li> вы можете произвести оплату при помощи платёжных систем <b>webmoney и yandex-деньги, карты сбербанк.</b></li>
</ul>
</p>



</div>
</div>

app/views/home/index.html.erb
<%= title("Мед на дом -- у нас вы можете купить натуральный мед с нашей пасеки! ") %>
<%= description(" В нашем интернет магазине вы можете приобрести мед оптом, купить мед и заказать доставку меда по всей России. Мы гарантируем, что наш мед натуральный и высшего качества. Так же у нас на сайте вы можете задать вопрос профессиональным пчеловодам. ")%>
<%#= render :partial => "home/article", :collection => @articles %>

			<div class="message">

				<h3> Уважаемые любители мёда!  </h3>
                    <br/>
                      Мы рады приветствовать вас в нашем медовом магазине!
                    <br/>
                    <br/>

                            <p>
                              Цель магазина «Мёд на дом» - обеспечить наших покупателей отличным продуктом из первых рук.
                              Мы занимаемся прямыми продажами натурального мёда непосредственно со своей пасеки, имеем многолетний опыт и знаем о мёде и продуктах пчеловодства практически всё. Мы дорожим своими клиентами и относимся к ним с тем же вниманием, какое уделяем качеству своей продукции. Добро пожаловать!
                            </p>
			</div><!-- END message -->
            <div class="products">
                            <%= render :partial => "stores/store", :collection => @stores %>
                        </div><!-- END products -->
                        <p class="split">
                          &nbsp;
                          <br/>
                        </p>
            <div class="posts">
                <h4>Статьи о мёде</h4>
                
                                <%- @articles.each do |article| %>
                                  <% if article.publish_on_main? %>
                  <div class="post">
                                      <h4><%= link_to article.name, category_article_path(article.category,article) %></h4>
                                      <p><%= raw truncate_html article.body, :length => 200 %></p>
                                        <%= link_to "Подробнее...", category_article_path(article.category,article), :class=>"more"%>
                </div><!-- END post -->
                                  <% end %>
                                <% end %>
            </div><!-- END posts -->

app/views/home/mayskiy_med.html.erb
<% content_for :map do %>
<script charset="utf-8" src="https://clck.yandex.ru/jclck/dtype=stred/pid=443/cid=71834/path=map/rnd=0.48028539191000164/*https://maps.yandex.ru/"></script>
<script src="http://api-maps.yandex.ru/2.0/?load=package.full&amp;lang=ru-RU" type="text/javascript"></script>
<script type="text/javascript">
        // Как только будет загружен API и готов DOM, выполняем инициализацию
        //http://maps.yandex.ru/-/CVVyVW2n
        ymaps.ready(init);

        function init () {
            var myMap = new ymaps.Map("map", {
                    center: [44.268141, 38.863351],
                    zoom: 14,
                    type: "yandex#hybrid"
                }),

                // Создаем метку. При создании метки указываем ее свойство -  текст для отображения в иконке.38.863351,44.268141
                myPlacemark = new ymaps.Placemark([44.269837, 38.86172], {
                    // Свойства
                    // Текст метки
                    iconContent: 'Наша пасека'
                }, {
                    // Опции
                    // Иконка метки будет растягиваться под ее контент
                    preset: 'twirl#blueStretchyIcon'
                });

         // В метод add можно передать строковый идентификатор
            // элемента управления и его параметры.
            myMap.controls
                // Кнопка изменения масштаба
                .add('zoomControl')
                // Список типов карты
                .add('typeSelector')
                // Кнопка изменения масштаба - компактный вариант
                // Расположим её справа
                //.add('smallZoomControl', { right: 5, top: 75 })
                // Стандартный набор кнопок
                .add('mapTools');

            // Также в метод add можно передать экземпляр класса, реализующего определенный элемент управления.
            // Например, линейка масштаба ('scaleLine')
            myMap.controls
                .add(new ymaps.control.ScaleLine())
                // В конструкторе элемента управления можно задавать расширенные
                // параметры, например, тип карты в обзорной карте
                .add(new ymaps.control.MiniMap({
                    type: 'yandex#publicMap'
                }));


            // Добавляем метки на карту
            myMap.geoObjects
                .add(myPlacemark)
                .add(myGeoObject);
        }
    </script>

<% end %>
<%= title("Майский мед 2013 года :: Мед на дом") %>
<%= description("Мы начинаем подготовку пасеки к первому в этом году сбору майского меда!") %>

<!-- Add jQuery library -->
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>

<!-- Add mousewheel plugin (this is optional) -->
<script type="text/javascript" src="/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>

<!-- Add fancyBox -->
<link rel="stylesheet" href="/fancybox/source/jquery.fancybox.css?v=2.1.4" type="text/css" media="screen" />
<script type="text/javascript" src="/fancybox/source/jquery.fancybox.pack.js?v=2.1.4"></script>

<!-- Optionally add helpers - button, thumbnail and/or media -->
<link rel="stylesheet" href="/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" type="text/css" media="screen" />
<script type="text/javascript" src="/fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
<script type="text/javascript" src="/fancybox/source/helpers/jquery.fancybox-media.js?v=1.0.5"></script>

<link rel="stylesheet" href="/fancybox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" type="text/css" media="screen" />
<script type="text/javascript" src="/fancybox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>

<div class="posts single">
  <h1>Майский мед 2013 года -- мы уже начали подготовку.</h1>
</div>

<div class="post">

  <p>

Вот и пришла весна нового 2013го года. В Краснодарском крае, там, где находится наша пасека, уже зацвели фруктовые деревья, лесные цветы и зазеленела трава. Пчёлы стали активнее вылетать на разведку и приносить первую пыльцу в улей. В эти весенние  месяцы мы проводим много работ на пасеке: ревизия пчелиных семей, их общего состояния, профилактика болезней пчёл и другие.

  </p>



  <div id="" style="clear: both; overflow: hidden; margin-bottom: 24px;">
    <p style="display: block;">
      <a class="fancybox" rel="gallery1" href="/images/med/1.JPG" title="Персиковый сад">
        <img src="/images/med/min/1.JPG" alt="Персиковый сад" width="180" height="135"/>
      </a>
      <a class="fancybox" rel="gallery1" href="/images/med/2.JPG" title="Веселая работа">
        <img src="/images/med/min/2.JPG" alt="Веселая работа" width="180" height="135"/>
      </a>
      <a class="fancybox" rel="gallery1" href="/images/med/3.JPG" title="Дымарь">
        <img src="/images/med/min/3.JPG" alt="Дымарь" width="180" height="135"/>
      </a>
    </p>
  </div>
  <p>

Но мы не только занимаемся подготовкой пчёл к новому сезону. Мы ещё и планируем передвижения нашей пасеки, продумываем маршрут для первого медосбора.

  </p>
  <p>

Полноценный медосбор в наших краях начинается с цветения кустарника клёна татарского (или черноклёна). У нас он зацветает в апреле. Потом мы собираем мёд с акации. Это и будет наш первый мёд, который все называют «майским». Состав майского мёда 2013 г. зависит от качества взятки, как с черноклёна, так и с акации. Бывает так, что в апреле-мае стоит тёплая и солнечная погода. Тогда мы делаем 2 качки:  черноклёновый мёд и акациевый. Иногда, если погода не такая удачная, у нас получается 1 качка, это майский мёд, в составе которого будет и черноклён и акация.

  </p>
  <div id="" style="clear: both; overflow: hidden; margin-bottom: 24px;">
    <p style="display: block;">
      <a class="fancybox" rel="gallery1" href="/images/med/4.JPG" title="Ищем матку">
        <img src="/images/med/min/4.JPG" alt="Ищем матку" width="180" height="135"/>
      </a>
      <a class="fancybox" rel="gallery1" href="/images/med/5.JPG" title="Начало работы">
        <img src="/images/med/min/5.JPG" alt="Начало работы" width="180" height="135"/>
      </a>
      <a class="fancybox" rel="gallery1" href="/images/med/6.JPG" title="Наши пчелы">
        <img src="/images/med/min/6.JPG" alt="Наши пчелы" width="180" height="135"/>
      </a>
    </p>
  </div>
  <p>

Как говорится: «весна да осень, на день погод восемь», и поэтому в это время года пчеловоды надеются на устойчивую погоду, чтобы успеть провести все необходимые работы на пасеке.

  </p>
  <p>

Мы тоже надеемся на лучшее и желаем и себе и остальным нашим коллегам-пчеловодам солнечной погоды, крепких и здоровых пчелосемей и минимум подмора! Потому-что, как говорит мой  папа-пчеловод: «в пчеловодстве упустишь день – потеряешь год!». За работу!

  </p>
  <div id="" style="clear: both; overflow: hidden; margin-bottom: 24px;">
    <p style="display: block;">
      <a class="fancybox" rel="gallery1" href="/images/med/7.JPG" title="Осмотр">
        <img src="/images/med/min/7.JPG" alt="Осмотр" width="180" height="135"/>
      </a>
      <a class="fancybox" rel="gallery1" href="/images/med/8.JPG" title="Природа просыпается">
        <img src="/images/med/min/8.JPG" alt="Природа просыпается" width="180" height="135" />
      </a>
      <a class="fancybox" rel="gallery1" href="/images/med/9.JPG" title="Труженницы">
        <img src="/images/med/min/9.JPG" alt="Труженницы" width="180" height="135" />
      </a>
    </p>
  </div>


<p>
  <script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
  <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="link" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,gplus"></div>
</p>

<p>
  <div id="map" style="width:600px; height:600px">
  </div>
</p>

<script type="text/javascript">
  $(document).ready(function() {
    $(".fancybox").fancybox({
      openEffect	: 'none',
      closeEffect	: 'none'
    });
  });
</script>