config/routes.rb
Jsovet::Application.routes.draw do

  resources :recipes do
    resources :recipes_comments do
      member do
        get 'publish'
      end
    end
  end

  resources :reviews do
    member do
      post :publish
    end
  end

  resources :answers
  resources :relative_questions, :only => [:index, :create]

  resources :questions do
    resources :relative_questions, :only => [:index, :create]
    resources :answers
    collection do
      get "hidden"
      post "sort"
    end
    member do
      get 'publish_on_main', 'not_publish_on_main'
    end
  end

  devise_for :users

  namespace :admin do
    resources :categories, :only => %w{index create edit update}
    resources :recipe_categories, :only => %w{index create edit update}
    resource :dashboard, :only => %w{show}, :controller => "dashboard"
    resources :articles, :only => "index"
    resources :stores
    resources :main_articles, :only => "index"
    resources :main_questions, :only => "index"
    resources :unpublished_articles, :only => "index"
    resources :questions, :only => "index"
    resources :containers
  end

  resources :categories, :only => %w{index} do
    resources :articles
  end

  resources :recipe_categories, :only => %w{index, show} do
    resources :recipes
  end

  resources :containers, :only => %w{index}

  resources :stores, :only => %w{show index} do
    collection do
      post "sort"
    end
  end
  resources :shoping_carts, :only => %w{index} do
    collection do
      get 'clear'
      get 'new_mail'
      post 'send_mail'
    end

    member do
      get 'add'
      get 'delete'
    end
  end

  resources :articles, :only => %w{new create edit update index} do

    collection do
      get 'my'
      post 'preview'
      post 'sort'
    end

    member do
      get 'publish', 'delete', 'publish_on_main', 'not_publish_on_main'
    end

    resources :comments, :only => %w{create update}
    resources :relative_articles, :only => %w{index create}
  end

  resources :images do
    collection do
      put "update_images"
    end
  end

  match 'search/index' => 'search#index', :as => :search
  match 'how_to_buy' => 'home#how_to_buy', :as => :how_to_buy
  get "mayskiy_med_2013" => "home#mayskiy_med", :as => :mayskiy
  get "contacts" => "home#contacts", :as => :contacts

  root :to => "home#index"
end

app/models/store.rb
require 'acts_as_list'
class Store < ActiveRecord::Base
  acts_as_list
  attr_accessor :product
  attr_accessible :name, :description, :where_from, :honey_sort,
                  :logo, :on_index, :on_top, :shown, :price, :price_three_liters, :price_one_liter, :product,
                  :prod, :fresh, :position, :logo_name, :gather_place,
                  :certificate


  has_attached_file :logo, :styles => {:big => "400x400>", :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :gather_place, :styles => {:big => "400x400>", :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :certificate, :styles => {:big => "600x900>", :medium => "300x300>", :thumb => "100x100>" }

  validates_presence_of :name, :description, :where_from,  :price, :price_three_liters, :price_one_liter
  #validates_presence_of :honey_sort, :if => Proc.new{ |store| store.product == "true" }



  scope :at_index, where(:on_index => true).order(:position)
  scope :at_top, where(:on_top => true)
  scope :shown, where(:shown => true).order(:position)

  def self.short_weight
    range = (100..1000)
    range.step(100).to_a
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < ApplicationController
  load_and_authorize_resource :store
  uses_tiny_mce :options => {
                            :theme => 'advanced',
                            :theme_advanced_resizing => true,
                            :theme_advanced_resize_horizontal => false,
                            :theme_advanced_toolbar_location => "top",
                            :theme_advanced_toolbar_align => "left",
                            :theme_advanced_statusbar_location => "bottom",
                            :theme_advanced_buttons1 => %w{ bold italic underline fontselect fontsizeselect formatselect newdocument},
                            :theme_advanced_buttons2 => %w{ justifyleft justifycenter justifyright bullist numlist undo redo }
                            }

  def index
    @stores = Store.order(:position)
    authorize! :update, @stores
  end

  def new
  end

  def create
    if @store.save
      redirect_to :action => :index, :notice => t("stores.successful.create")
    else
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @store.update_attributes(params[:store])
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def show
  end

  def delete
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_filter :add_crumb, :only => :show
  after_filter :authorize, :only => [:sort]
  load_and_authorize_resource :store, :except => [:sort]

  def index
    @stores = Store.shown
  end

  def show
    @store = Store.find(params[:id])
    add_breadcrumb @store.name, store_path(@store)
  end

  def sort
    params[:store].each_with_index do |id, index|
      Store.update_all({:position => index+1}, {:id => id})
    end
  render :nothing => true
  
  end

  private
  def add_crumb
    add_breadcrumb "Магазин мёда", stores_path
  end

end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper

  def yes_no(bool)
    bool == true ? "Да" : "Нет"
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/admin/stores/_form.html.erb
<% set_editor_comment %>
<%= semantic_form_for [:admin, @store], :html => {:multipart => true} do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.label :description %>
    <%= f.text_area :description, :class => "mceEditor", :size => "100x20" %>
    <%= f.input :where_from%>
    <%= f.input :price %>
    <%= f.input :price_three_liters %>
    <%= f.input :price_one_liter %>
    <%= f.input :logo_name %>
    <%= f.input :logo, :as => :file %>
    <%= f.input :gather_place, :as => :file %>
    <%= f.input :certificate, :as => :file %>
    <%= f.input :honey_sort, :as => :select, :collection => ( 1..7 ).to_a %>
    <li style="padding-left: 100px;">
      <% (1..7).to_a.each do |m|  %>
        <%= image_tag "/images/m#{m}.png", :title => m %>
      <% end %>
    </li>
  <% end %>
  <%= f.inputs do %>
    <%= f.input :on_index%>
    <%= f.input :on_top%>
    <%= f.input :fresh%>
    <%= f.input :shown%>
    <%= f.input :prod%>
  <% end %>
  <%= f.buttons %>
<% end %>

app/views/admin/stores/_stores.html.erb
<ul id="stores" data-update-url="<%= sort_stores_url %>">
  <% @stores.each do |store| %>
    <li id="store_<%= store.id %>">
      <span class="handle">[Перетащить]</span>
      <div class="post">
        <h4><%= store.name %></h2>
        <table class="border">
          <tr>
            <th>Наименование</th>
            <th>Откуда</th>
            <th>Цена</th>
            <th>Цвет</th>
            <th>Медонос</th>
            <th>На главной?</th>
            <th>Топ продаж?</th>
            <th>Свежий?</th>
            <th>Показываем</th>
            <th>Управление</th>
          </tr>	
          <tr>
            <td><%= store.name %></td>
            <td><%= store.where_from%></td>
            <td><%= store.price%></td>
            <td><%= sort_image store.honey_sort %></td>
            <td><%= link_to image_tag(store.logo.url(:thumb)), store.logo.url %></td>
            <td><%= yes_no store.on_index%></td>
            <td><%= yes_no store.on_top %></td>
            <td><%= yes_no store.fresh %></td>
            <td><%= yes_no store.shown %></td>
            <td><%= link_to t("edit"), edit_admin_store_path(store) %></td>
          </tr>
        </table>
      </div>
    </li>
  <% end %>
</ul>

app/views/admin/stores/edit.html.erb
<h1><%= t(".title") %></h1>
<%= render :partial => "form" %>

app/views/admin/stores/index.html.erb
<h1>Администраторская: Магазин</h1>

<br/>
<p>
  <%= link_to t("Добавить позицию"), new_admin_store_path%>
</p>
<br/>
<%= render :partial => "stores"%>

app/views/admin/stores/new.html.erb
<div class="post single">
  <h1><%= t(".title") %></h1>
  <%= render :partial => "form" %>
</div>

app/views/admin/stores/show.html.erb
<h1>Admin::Stores#show</h1>
<p>Find me in app/views/admin/stores/show.html.erb</p>