config/routes.rb
Jsovet::Application.routes.draw do

  resources :recipes do
    resources :recipes_comments do
      member do
        get 'publish'
      end
    end
  end

  resources :reviews do
    member do
      post :publish
    end
  end

  resources :answers
  resources :relative_questions, :only => [:index, :create]

  resources :questions do
    resources :relative_questions, :only => [:index, :create]
    resources :answers
    collection do
      get "hidden"
      post "sort"
    end
    member do
      get 'publish_on_main', 'not_publish_on_main'
    end
  end

  devise_for :users

  namespace :admin do
    resources :categories, :only => %w{index create edit update}
    resources :recipe_categories, :only => %w{index create edit update}
    resource :dashboard, :only => %w{show}, :controller => "dashboard"
    resources :articles, :only => "index"
    resources :stores
    resources :main_articles, :only => "index"
    resources :main_questions, :only => "index"
    resources :unpublished_articles, :only => "index"
    resources :questions, :only => "index"
    resources :containers
  end

  resources :categories, :only => %w{index} do
    resources :articles
  end

  resources :recipe_categories, :only => %w{index, show} do
    resources :recipes
  end

  resources :containers, :only => %w{index}

  resources :stores, :only => %w{show index} do
    collection do
      post "sort"
    end
  end
  resources :shoping_carts, :only => %w{index} do
    collection do
      get 'clear'
      get 'new_mail'
      post 'send_mail'
    end

    member do
      get 'add'
      get 'delete'
    end
  end

  resources :articles, :only => %w{new create edit update index} do

    collection do
      get 'my'
      post 'preview'
      post 'sort'
    end

    member do
      get 'publish', 'delete', 'publish_on_main', 'not_publish_on_main'
    end

    resources :comments, :only => %w{create update}
    resources :relative_articles, :only => %w{index create}
  end

  resources :images do
    collection do
      put "update_images"
    end
  end

  match 'search/index' => 'search#index', :as => :search
  match 'how_to_buy' => 'home#how_to_buy', :as => :how_to_buy
  get "mayskiy_med_2013" => "home#mayskiy_med", :as => :mayskiy
  get "contacts" => "home#contacts", :as => :contacts

  root :to => "home#index"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :body

  validates_presence_of :body

  belongs_to :question

  after_create {|answer| answer.question.update_attribute(:shown, true)}
end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base
  before_filter :find_question
  #belongs_to :question
  def create
    @answer = Answer.new(params[:answer])
    @answer.question = @question
    create!(:notice => t("answers.success.create")) { hidden_questions_path }
  end

  private
  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= semantic_form_for [ @question, @answer ] do |f| %>
  <%= f.inputs do %>
    <%= f.input :body %>
  <% end %>

  <%= f.buttons do %>
    <%= f.commit_button "Ответить" %>
  <% end %>
<% end %>

app/views/answers/edit.html.erb
<h1>Редактировать ответ</h1>

<%= render 'form' %>

<%= link_to 'Просмотреть вопрос', @question %> |
<%= link_to 'К списку', questions_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.body %></td>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<div class="posts single">
  <h1>Ответ на вопрос</h1>
</div>

<p>
  <%= @question.body %>
</p>

<%= render 'form' %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @answer.body %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>